GenericExecuteSynth "env DATA=\"$DATA\" VOICE=\"$VOICE\" /usr/bin/piper-dispatcher"
GenericLanguage "en"

# Debug "1"

GenericPunctNone ""
GenericPunctSome "--punct=\"()[]{};:\""
GenericPunctMost "--punct=\"()[]{};:\""
GenericPunctAll "--punct"

GenericCmdDependency "piper-tts"
GenericDefaultCharset "utf-8"

DefaultVoice "en/en_US/ryan/high/en_US-ryan-high"
GenericLanguage "en" "en_US" "utf-8"
AddVoice "en" "MALE1" "en/en_US/ryan/high/en_US-ryan-high"
